"""
CareFlow Day 1 Demo Script.

Demonstrates the complete pipeline:
  1. Load canonical demo case
  2. Generate traditional schedule
  3. Generate CareFlow schedule
  4. Print stress comparison
  5. Add an additional treatment cycle
  6. Re-run optimization (replan)
  7. Print before/after schedule summary

All numbers are generated by the actual financial engine.
No values are fabricated.
"""

import sys
import os

# Add backend/ to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from app.data.demo_cases import get_canonical_demo_case
from app.data.treatment_templates import get_chemotherapy_demo
from app.services.repayment_service import (
    calculate_traditional_schedule,
    calculate_careflow_schedule,
    reconstruct_completed_periods,
    calculate_careflow_schedule_from_balance,
)
from app.services.optimization_service import (
    apply_simulation_event,
    generate_explanations,
    calculate_comparison,
)
from app.services.loan_service import calculate_emi, calculate_remaining_balance
from app.schemas.simulation import SimulationEvent
from app.schemas.financial import OptimizationStatus


def fmt_inr(amount: float) -> str:
    """Format as Indian Rupees."""
    return f"Rs.{amount:>12,.0f}"


def print_schedule_table(schedule, title: str):
    print(f"\n  {title}")
    print(f"  {'Per':>3}  {'Medical':>10}  {'Payment':>10}  {'Interest':>9}  {'Principal':>10}  {'Balance':>10}  {'Deficit':>9}  {'Stress'}")
    print("  " + "-" * 95)
    for p in schedule:
        completed = " [done]" if p.is_completed else ""
        print(
            f"  {p.period:>3}  "
            f"{p.medical_expense:>10,.0f}  "
            f"{p.payment:>10,.0f}  "
            f"{p.interest:>9,.0f}  "
            f"{p.principal:>10,.0f}  "
            f"{p.ending_balance:>10,.0f}  "
            f"{p.projected_deficit:>9,.0f}  "
            f"{p.stress_level.value}{completed}"
        )


def main():
    print("\n" + "=" * 70)
    print("  CAREFLOW FINANCIAL ENGINE — DAY 1 DEMO")
    print("  Treatment doesn't follow an EMI schedule. Neither should repayment.")
    print("=" * 70)

    # ── Load canonical case ───────────────────────────────────────────────────
    case = get_canonical_demo_case()
    template = get_chemotherapy_demo()

    print(f"\n  Treatment:        {template.name}")
    print(f"  Loan Principal:   {fmt_inr(case.loan.principal)}")
    print(f"  Annual Rate:      {case.loan.annual_interest_rate}%")
    print(f"  Loan Periods:     {case.loan.remaining_periods} months")
    print(f"  Monthly Income:   {fmt_inr(case.income)}")
    print(f"  Household Exp:    {fmt_inr(case.monthly_household_expenses)}")
    print(f"\n  Treatment Costs (months 1-6):")
    for i, cost in enumerate(case.treatment_costs, 1):
        print(f"    M{i}: {fmt_inr(cost)}")

    standard_emi = calculate_emi(
        case.loan.principal,
        case.loan.annual_interest_rate,
        case.loan.remaining_periods,
    )
    print(f"\n  Standard EMI (if no CareFlow): {fmt_inr(standard_emi)}/month")

    # ── Traditional schedule ──────────────────────────────────────────────────
    print("\n" + "-" * 70)
    print("  TRADITIONAL (FIXED EMI) SCHEDULE")
    print("-" * 70)

    trad = calculate_traditional_schedule(case)
    print_schedule_table(trad.schedule, "Period-by-period breakdown:")

    tm = trad.metrics
    print(f"\n  Traditional Metrics:")
    print(f"    Peak projected deficit:   {fmt_inr(tm.peak_deficit)}")
    print(f"    Total projected deficit:  {fmt_inr(tm.total_deficit)}")
    print(f"    High-stress periods:      {tm.high_stress_periods}")
    print(f"    Critical-stress periods:  {tm.critical_stress_periods}")
    print(f"    Total interest paid:      {fmt_inr(tm.total_interest)}")
    print(f"    Total repayment:          {fmt_inr(tm.total_repayment)}")

    # ── CareFlow schedule ─────────────────────────────────────────────────────
    print("\n" + "-" * 70)
    print("  CAREFLOW ADAPTIVE SCHEDULE (LP-OPTIMIZED)")
    print("-" * 70)

    cf = calculate_careflow_schedule(case)

    if cf.optimization_status == OptimizationStatus.INFEASIBLE:
        print(f"\n  Optimization status: INFEASIBLE")
        print(f"  Reason: {cf.infeasibility_reason}")
        sys.exit(1)

    print_schedule_table(cf.schedule, f"Optimized schedule (status: {cf.optimization_status.value}):")

    cm = cf.metrics
    print(f"\n  CareFlow Metrics:")
    print(f"    Peak projected deficit:   {fmt_inr(cm.peak_deficit)}")
    print(f"    Total projected deficit:  {fmt_inr(cm.total_deficit)}")
    print(f"    High-stress periods:      {cm.high_stress_periods}")
    print(f"    Critical-stress periods:  {cm.critical_stress_periods}")
    print(f"    Total interest paid:      {fmt_inr(cm.total_interest)}")
    print(f"    Total repayment:          {fmt_inr(cm.total_repayment)}")
    print(f"    Extension periods used:   {cm.extension_periods}")

    # ── Comparison ────────────────────────────────────────────────────────────
    comparison = calculate_comparison(trad, cf)

    print("\n" + "-" * 70)
    print("  COMPARISON: TRADITIONAL vs CAREFLOW")
    print("-" * 70)
    direction = lambda x: ("+" if x > 0 else "") + f"{x:,.0f}"

    peak_note = "CareFlow lower" if comparison.peak_deficit_reduction > 0 else "No improvement"
    total_note = "CareFlow lower" if comparison.total_deficit_reduction > 0 else "No improvement"
    interest_note = "CareFlow higher (expected with variable schedule)" if comparison.interest_difference > 0 else "CareFlow lower"

    print(f"    Peak deficit reduction:   {fmt_inr(comparison.peak_deficit_reduction)}   ({peak_note})")
    print(f"    Total deficit reduction:  {fmt_inr(comparison.total_deficit_reduction)}   ({total_note})")
    print(f"    High-stress reduction:    {direction(comparison.high_stress_period_reduction)} periods")
    print(f"    Critical-stress reduction:{direction(comparison.critical_stress_period_reduction)} periods")
    print(f"    Interest difference:      {fmt_inr(comparison.interest_difference)}   ({interest_note})")
    print(f"    Tenure difference:        {comparison.tenure_difference:+d} periods")

    # ── Explanations ──────────────────────────────────────────────────────────
    explanations = generate_explanations(
        careflow_schedule=cf.schedule,
        traditional_emi=standard_emi,
        original_periods=case.loan.remaining_periods,
        medical_expenses=case.treatment_costs,
    )
    if explanations:
        print("\n  Key payment decisions:")
        for e in explanations[:5]:
            print(f"    Period {e.period} [{e.explanation_type}]: {e.message}")

    # ── Treatment event: additional cycle ────────────────────────────────────
    print("\n" + "=" * 70)
    print("  TREATMENT EVENT: Additional Cycle in Period 7 (+75,000)")
    print("=" * 70)

    event = SimulationEvent(
        event_type="additional_cycle",
        target_period=7,
        additional_cost=75_000,
        description="Unforeseen additional chemotherapy cycle required.",
    )

    n_completed = 3
    completed_payments = [p.payment for p in cf.schedule[:n_completed]]
    completed_schedule = reconstruct_completed_periods(
        case=case,
        n_completed=n_completed,
        completed_payments=completed_payments,
    )

    remaining_balance = calculate_remaining_balance(
        case.loan.principal,
        case.loan.annual_interest_rate,
        completed_payments,
    )

    print(f"\n  Completed periods:     {n_completed}")
    print(f"  Remaining balance:     {fmt_inr(remaining_balance)}")
    print(f"  Event:                 {event.event_type} at period {event.target_period}, cost {fmt_inr(event.additional_cost)}")

    updated_medical = apply_simulation_event(
        case.treatment_costs, event, completed_periods=n_completed
    )
    future_medical = updated_medical[n_completed:]
    n_remaining = case.loan.remaining_periods - n_completed

    # ── Replan ────────────────────────────────────────────────────────────────
    replanned = calculate_careflow_schedule_from_balance(
        case=case,
        remaining_balance=remaining_balance,
        n_remaining=n_remaining,
        future_medical=future_medical,
        period_offset=n_completed,
    )

    if replanned.optimization_status == OptimizationStatus.INFEASIBLE:
        print(f"\n  Replan status: INFEASIBLE")
        print(f"  Reason: {replanned.infeasibility_reason}")
    else:
        print(f"\n  Replan status: {replanned.optimization_status.value.upper()}")

        full_schedule = completed_schedule + replanned.schedule

        print_schedule_table(
            full_schedule,
            f"Full schedule after treatment event (completed periods + replanned):"
        )

        rm = replanned.metrics
        print(f"\n  Replanned Future Metrics:")
        print(f"    Peak projected deficit:   {fmt_inr(rm.peak_deficit)}")
        print(f"    Total projected deficit:  {fmt_inr(rm.total_deficit)}")
        print(f"    High-stress periods:      {rm.high_stress_periods}")
        print(f"    Critical-stress periods:  {rm.critical_stress_periods}")
        print(f"    Extension periods used:   {rm.extension_periods}")
        print(f"    Final balance:            {fmt_inr(replanned.schedule[-1].ending_balance)}")

    print("\n" + "=" * 70)
    print("  DEMO COMPLETE")
    print("  All values generated by the CareFlow deterministic financial engine.")
    print("  No values were fabricated or hardcoded.")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()
